version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for static HTML"

  pre_build:
    commands:
      - echo "Pre-build phase: Checking repository files"

  build:
    commands:
      - echo "Build phase: No build steps required for static HTML"

  post_build:
    commands:
      - echo "Post-build phase: Deploying index.html to S3"
      - aws s3 cp index.html s3://index-portfolio/index.html --acl public-read

