version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies (none required)."
  pre_build:
    commands:
      - echo "Pre-build: Validating environment."
      - aws --version
  build:
    commands:
      - echo "Build: No build steps required for static files."
  post_build:
    commands:
      - echo "Post-build: 'Nothing to deploy, as no artifacts are used."'
