version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  pre_build:
    commands:
      - echo "Pre-build phase: Listing files"
      - ls -al
  build:
    commands:
      - echo "Build phase: Nothing to compile"
  post_build:
    commands:
      - echo "Post-build phase: Deploying to S3"
      - aws s3 cp index.html s3://index-portfolio/index.html --acl public-read
