version: 0.2

phases:
  install:
    commands:
      - echo "Starting the build process..."

  pre_build:
    commands:
      - echo "Running pre-build tasks..."

  build:
    commands:
      - echo "Copying index.html to build directory"
      - mkdir -p build
      - cp index.html build/
      - echo "Build complete."

  post_build:
    commands:
      - echo "Post-build tasks can be added here, if needed."
